/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links': RouteRecordInfo<'/links', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/geekgame-2024': RouteRecordInfo<'/posts/geekgame-2024', '/posts/geekgame-2024', Record<never, never>, Record<never, never>>,
    '/posts/geekgame-2024-iot': RouteRecordInfo<'/posts/geekgame-2024-iot', '/posts/geekgame-2024-iot', Record<never, never>, Record<never, never>>,
    '/posts/valaxy-1st-issue': RouteRecordInfo<'/posts/valaxy-1st-issue', '/posts/valaxy-1st-issue', Record<never, never>, Record<never, never>>,
    '/posts/valaxy-md-tweak': RouteRecordInfo<'/posts/valaxy-md-tweak', '/posts/valaxy-md-tweak', Record<never, never>, Record<never, never>>,
    '/posts/valaxy-time-metadata': RouteRecordInfo<'/posts/valaxy-time-metadata', '/posts/valaxy-time-metadata', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
