name: Deploy to Azure

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: "blueg-blog"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "api"
  NODE_VERSION: "20.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Blogs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v4

      - name: Build Blog
        env:
          TZ: Asia/Shanghai
        run: |
          pnpm install
          pnpm build

      - name: Build Functions
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build
          popd

      - name: Deploy Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-functions
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Deploy Static Web App
        id: deploy-static
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist" # App source code path
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
